---
spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cdc;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.H2Dialect
        storage_engine: innodb
        format_sql: false
        show_sql: true
        globally_quoted_ids: true
        enable_lazy_load_no_trans: true
        generate_statistics: false
        hbm2ddl:
          auto: update
